### ISSUE TITLE
Custom fonts loaded via the theme stylesheet are blocked by the CORS policy

### ISSUE THREAD

**Issue by sergei-maertens** [GPP-Woo/GPP-burgerportaal#91]
Taken:
- [ ] Environment variable toevoegen en uitlezen
- [ ] Waarde toevoegen aan csp directive
- [ ] Documenteren

My docker compose (with a `.env` file for the secrets):

```yaml
x-welcome: &x-welcome |
  <h1 class="utrecht-headng-1">Openbare documenten</h1>

  <p class="utrecht-paragraph">
    Demo-omgeving voor het doorzoeken van openbaar gemaakte documenten. Deze omgeving
    is gekoppeld met de Maykin testinstantie van GPP-zoeken. De GPP-publicatiebank
    is verantwoordelijk voor het indexeren van documenten.
  </p>

services:
  assets:
    image: docker.io/nginxinc/nginx-unprivileged:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ${THEME_ROOT}:/usr/share/nginx/html:ro
    ports:
      - "8081:8080"

  gpp-burgerportaal:
    image: ghcr.io/gpp-woo/gpp-burgerportaal:main
    environment:
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ODRC_BASE_URL: "${ODRC_BASE_URL}"
      ODRC_API_KEY: "${ODRC_API_KEY}"
      SEARCH_BASE_URL: "${SEARCH_BASE_URL}"
      SEARCH_API_KEY: "${SEARCH_API_KEY}"
      RESOURCES:GEMEENTE_NAAM: Maykin
      RESOURCES:GEMEENTE_LOGO_URL: http://localhost:8081/assets/logo.svg
      RESOURCES:GEMEENTE_FAVICON_URL: http://localhost:8081/assets/favicon.png
      RESOURCES:GEMEENTE_MAIN_IMAGE_URL: https://media.umbraco.io/umbracowijktuin/kawlgnjx/2023-04-05-header-3.jpg
      RESOURCES:GEMEENTE_DESIGN_TOKENS_URL: http://localhost:8081/assets/theme.css
      RESOURCES:GEMEENTE_THEME_NAAM: maykin-theme
      RESOURCES:GEMEENTE_WEBSITE_URL: https://opengem.nl
      RESOURCES:GEMEENTE_PRIVACY_URL: https://opengem.nl/privacy/
      RESOURCES:GEMEENTE_CONTACT_URL: https://opengem.nl/contact/
      RESOURCES:GEMEENTE_WELKOM: *x-welcome
      RESOURCES:TOEGANKELIJKHEIDSVERKLARING_REGISTER_URL: https://www.toegankelijkheidsverklaring.nl/register
    ports:
      - "8080:8080"

```

Note that `RESOURCES:GEMEENTE_DESIGN_TOKENS_URL` is set to a custom CSS file, which has among others the following content:

```css
@font-face {
  font-family: titillium;
  src:
    url(./fonts/titillium-regular-webfont.woff2) format('woff2'),
    url(./fonts/titillium-regular-webfont.woff) format('woff');
  font-weight: 400;
  font-style: normal;
}

@font-face {
  font-family: titillium;
  src:
    url(./fonts/titillium-bold-webfont.woff2) format('woff2'),
    url(./fonts/titillium-bold-webfont.woff) format('woff');
  font-weight: 700;
  font-style: normal;
}

/**
 * Do not edit directly, this file was auto-generated.
 */
.maykin-theme {
  --utrecht-typography-sans-serif-font-family: titillium,Helvetica,Arial,sans-serif;
  --utrecht-document-font-family: titillium,Helvetica,Arial,sans-serif;
}
```

However, the font-download is blocked by the CORS policy directive `"font-src 'self'"`.

![Image](https://github.com/user-attachments/assets/c8019f58-0d8e-43d2-a55f-88768b892405)
